
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```
##Purpose: 
Figure 2e  --  Cost

#Protocol: 

###1. Load the following packages:

```{r packages}

library(tidyverse)
library(ggsignif)
library(ggrepel)
library(edgeR)
library(genefilter)
library(grid)
library(gridExtra)
library(ggsci)

fig_path<-"/data/share/htp/prime-seq_Paper/Fig_cost/"

#prevent scientific notation
options(scipen=999)

```

###2. Load following functions:


```{r functions}
theme_pub <- theme_bw() + theme(
                                     plot.title = element_text(hjust = 0.5, size=18, face="bold"),
                                     axis.text = element_text(colour="black", size=14), 
                                     axis.title=element_text(size=16,face="bold"), 
                                     legend.text=element_text(size=14),
                                     legend.position="right",
                                     axis.line.x = element_line(colour = "black"), 
                                     axis.line.y = element_line(colour = "black"),
                                     strip.background=element_blank(), 
                                     strip.text=element_text(size=16))  


```

## Price Plots

###3. Lysis Plot


```{r load_counts}
method_colors<-c("gray20","gray30","gray40","gray50","gray60","gray70","gray80","#008080")
names(method_colors)<-c("SMARTer Stranded Total RNA",
                                              "SMART-Seq v4",
                                              "TruSeq",
                                              "TruSeq Stranded",
                                              "Illumina Stranded",
                                              "brb-seq (Nextera)",
                                              "brb-seq (custom)",
                                              "prime-seq")

possiblesamples <- read.csv(paste0(fig_path,"method_cost.csv"), header = T, stringsAsFactors = F)

#factor
possiblesamples$Method<-factor(possiblesamples$Method,levels=(c("SMARTer Stranded Total RNA",
                                              "SMART-Seq v4",
                                              "TruSeq",
                                              "TruSeq Stranded",
                                              "Illumina Stranded",
                                              "brb-seq (Nextera)",
                                              "brb-seq (custom)",
                                              "prime-seq")))

possiblesamples_bar <- ggplot(possiblesamples, aes(x=Method, y=Samples))+
    geom_bar(aes(fill=Method), stat = "identity", width=0.6)+
    geom_label(aes(x= Method, y = Samples+25, label = Samples), data = possiblesamples)+
    ylab("Number of Samples") +
    scale_fill_manual(values = method_colors)+
    scale_x_discrete(name = 'RNA-seq Method', 
                     breaks = c('SMARTer Stranded Total RNA', 'SMART-Seq v4', 'TruSeq', 'TruSeq Stranded', 'Illumina Stranded', 'brb-seq (Nextera)','brb-seq (custom)','prime-seq'), 
                     labels = c('SMARTer\nStranded\nTotal RNA', 'SMART-Seq\n(v4)', 'TruSeq', 'TruSeq\nStranded', 'Illumina\nStranded','brb-seq\n(Nextera)','brb-seq\n(custom)','prime-seq'))+
    theme_pub+
    ggtitle("Experiment Sample Size with a Set Budget ($500)")+
    theme(legend.position= "none",
          panel.grid.major.x = element_blank()) 


ggsave(possiblesamples_bar,
device = "pdf",
path = fig_path,
width = 300,
height = 150,
units = "mm",
filename = "Fig6A.pdf"
)

```
